// admin-poratl-ui/src/components/ui/Toast.tsx
import { useToast, type Toast } from '../../hooks/useToast';

export function Toast() {
  const { toasts } = useToast();

  return (
    <div className="toast-container">
      {toasts.map((toast) => (
        <ToastItem key={toast.id} toast={toast} />
      ))}
    </div>
  );
}

function ToastItem({ toast }: { toast: Toast }) {
  const getIcon = () => {
    switch (toast.type) {
      case 'success':
        return '✓';
      case 'error':
        return '✕';
      case 'warning':
        return '⚠';
      case 'info':
        return 'ℹ';
    }
  };

  return (
    <div className={`toast toast-${toast.type}`}>
      <span className="toast-icon">{getIcon()}</span>
      <span className="toast-message">{toast.message}</span>
      <button type="button" className="toast-close" aria-label="Close">
        ×
      </button>
    </div>
  );
}

// driver-portal-frontend/src/app/core/toast/toast.component.ts
import { Component, ChangeDetectionStrategy, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ToastService, Toast } from './toast.service';

@Component({
  selector: 'app-toast',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './toast.component.html',
  styleUrls: ['./toast.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToastComponent {
  protected toastService = inject(ToastService);

  icon(type: Toast['type']): string {
    const icons: Record<Toast['type'], string> = {
      success: '✓',
      error: '✕',
      warning: '⚠',
      info: 'ℹ',
    };
    return icons[type];
  }

  dismiss(id: number) {
    this.toastService.dismiss(id);
  }
}

<div class="toast-container" aria-live="polite">
  <div *ngFor="let toast of toastService.toasts()" class="toast-item" [ngClass]="'toast-' + toast.type">
    <span class="toast-icon">{{ icon(toast.type) }}</span>
    <span class="toast-message">{{ toast.message }}</span>
    <button class="toast-close" type="button" (click)="dismiss(toast.id)" aria-label="Dismiss">&times;</button>
  </div>
</div>
